"""initial_schema

Revision ID: 2e78c9e49e4c
Revises: 
Create Date: 2026-03-24 18:16:29.618194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2e78c9e49e4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.Enum('CLIENT', 'COUTURIER', 'VENDEUR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('mensurations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('morphologie', sa.String(length=50), nullable=True),
    sa.Column('tranche_age', sa.String(length=20), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('events_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_analytics_created_at'), 'events_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_analytics_entity_id'), 'events_analytics', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_analytics_event_type'), 'events_analytics', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_analytics_id'), 'events_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_events_analytics_user_id'), 'events_analytics', ['user_id'], unique=False)
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('produits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('nb_likes', sa.Integer(), nullable=False),
    sa.Column('nb_commentaires', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_id'), 'outfits', ['id'], unique=False)
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('COUTURIER', 'BOUTIQUE', 'MARQUE', name='shoptype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('specialites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_delais', sa.Float(), nullable=False),
    sa.Column('score_qualite', sa.Float(), nullable=False),
    sa.Column('score_communication', sa.Float(), nullable=False),
    sa.Column('nb_avis', sa.Integer(), nullable=False),
    sa.Column('nb_commandes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_nom'), 'shops', ['nom'], unique=False)
    op.create_table('creation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos_modele', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photo_tissu', sa.String(length=512), nullable=True),
    sa.Column('mensurations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statut', sa.Enum('OUVERTE', 'DEVIS_RECUS', 'COUTURIER_SELECTIONNE', 'EN_COURS', 'TERMINEE', 'ANNULEE', name='creationrequeststatut'), nullable=False),
    sa.Column('option_diffusion', sa.String(length=20), nullable=False),
    sa.Column('couturier_favori_id', sa.Integer(), nullable=True),
    sa.Column('devis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('couturier_selectionne_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['couturier_favori_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['couturier_selectionne_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creation_requests_client_id'), 'creation_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_creation_requests_id'), 'creation_requests', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRET_A_PORTER', 'SUR_MESURE', name='ordertype'), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACCEPTEE', 'EN_COURS', 'EXPEDIE', 'LIVRE', 'CONFIRME', 'LITIGE', 'ANNULE', 'REMBOURSE', name='orderstatut'), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('penalite', sa.Integer(), nullable=False),
    sa.Column('escrow_statut', sa.Enum('EN_ATTENTE', 'BLOQUE', 'LIBERE', 'REMBOURSE', 'LITIGE', name='escrowstatut'), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adresse_livraison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_livraison_promise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_livraison_reelle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jalons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note_client', sa.Text(), nullable=True),
    sa.Column('note_vendeur', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_reference'), 'orders', ['reference'], unique=True)
    op.create_index(op.f('ix_orders_shop_id'), 'orders', ['shop_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.Enum('HOMME', 'FEMME', 'ENFANT', name='productcategorie'), nullable=False),
    sa.Column('occasion', sa.Enum('CASUAL', 'BUREAU', 'CEREMONIE', 'TRADITIONNEL', 'SPORT', 'MARIAGE', name='productoccasion'), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('tissu', sa.String(length=100), nullable=True),
    sa.Column('prix', sa.Integer(), nullable=False),
    sa.Column('prix_promo', sa.Integer(), nullable=True),
    sa.Column('promo_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tailles_guide', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mensurations_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sur_mesure', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('nb_vues', sa.Integer(), nullable=False),
    sa.Column('nb_likes', sa.Integer(), nullable=False),
    sa.Column('nb_commandes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_shop_id'), 'products', ['shop_id'], unique=False)
    op.create_index(op.f('ix_products_titre'), 'products', ['titre'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('operateur', sa.Enum('WAVE', 'ORANGE_MONEY', 'MTN_MONEY', 'CARTE', name='paymentoperateur'), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'SUCCES', 'ECHEC', 'REMBOURSE', name='paymentstatut'), nullable=False),
    sa.Column('ref_cinetpay', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('ref_cinetpay')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url_cloudinary', sa.String(length=512), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('angle', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('score_delais', sa.Float(), nullable=False),
    sa.Column('score_qualite', sa.Float(), nullable=False),
    sa.Column('score_communication', sa.Float(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_shop_id'), 'reviews', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_shop_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_products_titre'), table_name='products')
    op.drop_index(op.f('ix_products_shop_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_shop_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_creation_requests_id'), table_name='creation_requests')
    op.drop_index(op.f('ix_creation_requests_client_id'), table_name='creation_requests')
    op.drop_table('creation_requests')
    op.drop_index(op.f('ix_shops_nom'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_events_analytics_user_id'), table_name='events_analytics')
    op.drop_index(op.f('ix_events_analytics_id'), table_name='events_analytics')
    op.drop_index(op.f('ix_events_analytics_event_type'), table_name='events_analytics')
    op.drop_index(op.f('ix_events_analytics_entity_id'), table_name='events_analytics')
    op.drop_index(op.f('ix_events_analytics_created_at'), table_name='events_analytics')
    op.drop_table('events_analytics')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
