"""ajout seuil stock faible produit

Revision ID: 3dada7d8544e
Revises: c8e8de0b6aa8
Create Date: 2026-08-20 13:31:58.271658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3dada7d8544e'
down_revision: Union[str, None] = 'c8e8de0b6aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seuil_stock_faible', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'seuil_stock_faible')
    # ### end Alembic commands ###
