"""premiere_migration

Revision ID: 65b50280e3ce
Revises: 9b90a7d1caf1
Create Date: 2026-05-31 14:54:02.696351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65b50280e3ce'
down_revision: Union[str, None] = '9b90a7d1caf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=16), nullable=False),
    sa.Column('is_globally_active', sa.Boolean(), nullable=False),
    sa.Column('default_active', sa.Boolean(), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_slug'), 'modules', ['slug'], unique=True)
    op.create_table('entity_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_slug', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_slug'], ['modules.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_slug', 'entity_type', 'entity_id', name='uq_entity_module')
    )
    op.create_index(op.f('ix_entity_modules_module_slug'), 'entity_modules', ['module_slug'], unique=False)
    op.create_table('payment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('nb_tranches', sa.Integer(), nullable=False),
    sa.Column('acompte_percent', sa.Integer(), nullable=False),
    sa.Column('intervalle_jours', sa.Integer(), nullable=False),
    sa.Column('montant_min', sa.Integer(), nullable=False),
    sa.Column('montant_max', sa.Integer(), nullable=True),
    sa.Column('frais_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('couleur_principale', sa.String(length=7), nullable=False),
    sa.Column('couleur_secondaire', sa.String(length=7), nullable=False),
    sa.Column('couleur_fond', sa.String(length=7), nullable=False),
    sa.Column('couleur_texte', sa.String(length=7), nullable=False),
    sa.Column('couleur_accent', sa.String(length=7), nullable=False),
    sa.Column('police_titres', sa.String(length=64), nullable=False),
    sa.Column('police_corps', sa.String(length=64), nullable=False),
    sa.Column('banniere_url', sa.String(length=512), nullable=True),
    sa.Column('banniere_public_id', sa.String(length=256), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('logo_public_id', sa.String(length=256), nullable=True),
    sa.Column('slogan', sa.String(length=160), nullable=True),
    sa.Column('message_accueil', sa.String(length=512), nullable=True),
    sa.Column('a_propos', sa.Text(), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_table('order_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_plan_id', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Integer(), nullable=False),
    sa.Column('montant_paye', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('tranches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_installment_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=False),
    sa.Column('paye_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['order_installment_id'], ['order_installments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tranches')
    op.drop_table('order_installments')
    op.drop_table('shop_themes')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_entity_modules_module_slug'), table_name='entity_modules')
    op.drop_table('entity_modules')
    op.drop_index(op.f('ix_modules_slug'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
