"""suppression champ site web theme boutique

Revision ID: 8134e29bdf4e
Revises: 3dada7d8544e
Create Date: 2026-08-20 18:24:01.674233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8134e29bdf4e'
down_revision: Union[str, None] = '3dada7d8544e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_themes', 'site_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_themes', sa.Column('site_web', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
