"""ajout coordonnees contact theme boutique

Revision ID: c8e8de0b6aa8
Revises: f3ddf4f7ffff
Create Date: 2026-08-20 12:06:31.514859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8e8de0b6aa8'
down_revision: Union[str, None] = 'f3ddf4f7ffff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_themes', sa.Column('telephone_contact', sa.String(length=32), nullable=True))
    op.add_column('shop_themes', sa.Column('whatsapp', sa.String(length=32), nullable=True))
    op.add_column('shop_themes', sa.Column('instagram', sa.String(length=128), nullable=True))
    op.add_column('shop_themes', sa.Column('site_web', sa.String(length=256), nullable=True))
    op.add_column('shop_themes', sa.Column('horaires', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_themes', 'horaires')
    op.drop_column('shop_themes', 'site_web')
    op.drop_column('shop_themes', 'instagram')
    op.drop_column('shop_themes', 'whatsapp')
    op.drop_column('shop_themes', 'telephone_contact')
    # ### end Alembic commands ###
