"""ajout champ tiktok theme boutique

Revision ID: d2a777896437
Revises: 8134e29bdf4e
Create Date: 2026-08-20 18:36:45.854236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2a777896437'
down_revision: Union[str, None] = '8134e29bdf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_themes', sa.Column('tiktok', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_themes', 'tiktok')
    # ### end Alembic commands ###
