"""ajout negociation et delai confection sur orders

Revision ID: f152a2d9d93a
Revises: 52310d43a704
Create Date: 2026-06-28 17:40:19.872169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f152a2d9d93a'
down_revision: Union[str, None] = '52310d43a704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('prix_propose', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('prix_propose_statut', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('negociation_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delai_confection_jours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delai_confection_jours')
    op.drop_column('orders', 'negociation_deadline')
    op.drop_column('orders', 'prix_propose_statut')
    op.drop_column('orders', 'prix_propose')
    # ### end Alembic commands ###
