"""negociation conversation et plancher produit

Revision ID: f3ddf4f7ffff
Revises: c1b4a3e2f9d0
Create Date: 2026-08-19 08:47:55.599529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3ddf4f7ffff'
down_revision: Union[str, None] = 'c1b4a3e2f9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column(
        'negociations', postgresql.JSONB(astext_type=sa.Text()),
        nullable=False, server_default='[]',
    ))
    op.drop_column('orders', 'prix_propose')
    op.drop_column('orders', 'prix_propose_statut')
    op.drop_column('orders', 'negociation_deadline')
    op.add_column('products', sa.Column('prix_plancher_negociation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'prix_plancher_negociation')
    op.add_column('orders', sa.Column('negociation_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('prix_propose_statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('prix_propose', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'negociations')
    # ### end Alembic commands ###
